"""empty message

Revision ID: 90b26b0d2613
Revises: 
Create Date: 2021-06-04 03:52:37.283233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b26b0d2613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('store', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_table('meals')
    op.alter_column('message', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('message', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('message', 'message',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('message', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'message',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('message', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('message', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_table('meals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=30), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('image', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_table('repas')
    # ### end Alembic commands ###
